# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openrun < Formula
  desc ""
  homepage "https://openrun.dev"
  version "0.16.6"

  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openrundev/openrun/releases/download/v0.16.6/openrun-v0.16.6-darwin-amd64.tar.gz"
      sha256 "458391e4adfcfb6d55a9c40ca81a7e9a2b0063253a28b44875d5efdd7780403b"

      def install
        bin.install "openrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openrundev/openrun/releases/download/v0.16.6/openrun-v0.16.6-darwin-arm64.tar.gz"
      sha256 "25369404f7ad009d127ea54a1746da6b4fa4dfb2a6d8c5d9d217a13ba91e6b2b"

      def install
        bin.install "openrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openrundev/openrun/releases/download/v0.16.6/openrun-v0.16.6-linux-amd64.tar.gz"
      sha256 "40557dd7a3fce6fc051af0cfbce0491e55ad4103a0c120a0b3903cc6249ecbee"
      def install
        bin.install "openrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openrundev/openrun/releases/download/v0.16.6/openrun-v0.16.6-linux-arm64.tar.gz"
      sha256 "f733a0f43ea718c993846aff1eee96bb69f1492be0fc4eb1a64c70bc29ab39f7"
      def install
        bin.install "openrun"
      end
    end
  end

  def post_install
    unless File.exist?("#{etc}/openrun.toml")
      pid = spawn("#{opt_bin}/openrun password", out: "#{etc}/openrun.toml")
      puts "********** Initializing \"admin\" user **********"
      Process.wait(pid)
      puts "************* Save this password ****************"

      mkcert_path = `which mkcert`.chomp
      unless mkcert_path.empty?
        system("mkdir -p #{HOMEBREW_PREFIX}/var/openrun/config/certificates")
        system("#{mkcert_path} -install")
        system("#{mkcert_path} -cert-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.crt -key-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.key localhost 127.0.0.1 \"*.localhost\"")
        puts "Created localhost TLS certificates"
      end
    end
  end

  service do
    run [ opt_bin/"openrun", "server", "start" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/openrun.log"
    error_log_path var/"log/openrun.log"
  end
end
