# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openrun < Formula
  desc ""
  homepage "https://openrun.dev"
  version "0.17.0"

  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openrundev/openrun/releases/download/v0.17.0/openrun-v0.17.0-darwin-amd64.tar.gz"
      sha256 "dc3a6def01f8b5a6a2eb55de1148123215af01482c1ef6cd00247f0eb36f677e"

      def install
        bin.install "openrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openrundev/openrun/releases/download/v0.17.0/openrun-v0.17.0-darwin-arm64.tar.gz"
      sha256 "2b7315205813a35efacd8b08bace3d25ac96546facaf32f7d68666f1dbe0e8fa"

      def install
        bin.install "openrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openrundev/openrun/releases/download/v0.17.0/openrun-v0.17.0-linux-amd64.tar.gz"
      sha256 "73f01dad937d50ffd31268ade90e219f1e137fe4c58f4cd8e2b9448abe1477b8"
      def install
        bin.install "openrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openrundev/openrun/releases/download/v0.17.0/openrun-v0.17.0-linux-arm64.tar.gz"
      sha256 "6cdd3fc83ea9b461746511c4800f0d8cb6f971938e0455f13545dd5a61a291bf"
      def install
        bin.install "openrun"
      end
    end
  end

  def post_install
    unless File.exist?("#{etc}/openrun.toml")
      pid = spawn("#{opt_bin}/openrun password", out: "#{etc}/openrun.toml")
      puts "********** Initializing \"admin\" user **********"
      Process.wait(pid)
      puts "************* Save this password ****************"

      mkcert_path = `which mkcert`.chomp
      unless mkcert_path.empty?
        system("mkdir -p #{HOMEBREW_PREFIX}/var/openrun/config/certificates")
        system("#{mkcert_path} -install")
        system("#{mkcert_path} -cert-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.crt -key-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.key localhost 127.0.0.1 \"*.localhost\"")
        puts "Created localhost TLS certificates"
      end
    end
  end

  service do
    run [ opt_bin/"openrun", "server", "start" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/openrun.log"
    error_log_path var/"log/openrun.log"
  end
end
