# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openrun < Formula
  desc ""
  homepage "https://openrun.dev"
  version "0.18.15"

  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openrundev/openrun/releases/download/v0.18.15/openrun-v0.18.15-darwin-amd64.tar.gz"
      sha256 "4fb24934ca7022fc56f02ca3b11b1d23dadf3460acf627e4cf8c43d656e6ad19"

      def install
        bin.install "openrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openrundev/openrun/releases/download/v0.18.15/openrun-v0.18.15-darwin-arm64.tar.gz"
      sha256 "0abe43b244f6b9a000031e41c8f343054937856ded0e69bf366970c0c7c86fa5"

      def install
        bin.install "openrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openrundev/openrun/releases/download/v0.18.15/openrun-v0.18.15-linux-amd64.tar.gz"
      sha256 "e9acb3a7135b15d3bc4871c1af6eefc1d4a54c03bdde151bac5c9fa772b88f82"
      def install
        bin.install "openrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openrundev/openrun/releases/download/v0.18.15/openrun-v0.18.15-linux-arm64.tar.gz"
      sha256 "ac20ad5130f2067078a668fab8594674ff3577587cefc48ce5b35ab417eb2670"
      def install
        bin.install "openrun"
      end
    end
  end

  def post_install
    unless File.exist?("#{etc}/openrun.toml")
      pid = spawn("#{opt_bin}/openrun password", out: "#{etc}/openrun.toml")
      puts "********** Initializing \"admin\" user **********"
      Process.wait(pid)
      puts "************* Save this password ****************"

      mkcert_path = `which mkcert`.chomp
      unless mkcert_path.empty?
        system("mkdir -p #{HOMEBREW_PREFIX}/var/openrun/config/certificates")
        system("#{mkcert_path} -install")
        system("#{mkcert_path} -cert-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.crt -key-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.key localhost 127.0.0.1 \"*.localhost\"")
        puts "Created localhost TLS certificates"
      end
    end
  end

  service do
    run [ opt_bin/"openrun", "server", "start" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/openrun.log"
    error_log_path var/"log/openrun.log"
  end
end
